research_root_email: ENC[AES256_GCM,data:I+1AQP788mthqGkUB2RMAYHDE3LMJB+pmP/HSm+/Xg==,iv:F2vhGjjOJj0YTO81YB1bsUQ1tG9CkKmxU/zFi4jZBOI=,tag:KEbQP87YYtU2OabTw7Hfzg==,type:str]
sops:
  age:
    - recipient: age1pk0z5nauz3extrv3kqqksl6yf433nk66jq9s3kk6xz07nnwxcddq9z7vhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYm05TVFqeWlqeEQrVjNx
        ZFAvQWVkVEJLdllnemhhbU5UdmVPMW9MMDA4Cjd5ZDlZMW5CbEdVY0g3d0lQektU
        Tm55MVpXMHBLVDZpMDhsZHk1RGJDRjQKLS0tIFBaRjNJRmtBWWVMMVlNdkhiazUw
        UFVBMXhGRkxyMm9MV2JwUTFxaDI1dDAKn5a7Uv7+vnKq+tPQ/IM8ACDZ2cnxmyTU
        6RAfrN932kWJTeAM/K6n6nbxlCwNTzgZ7/3Y0+WeLX0LkkjY8FLknA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-15T15:30:17Z"
  mac: ENC[AES256_GCM,data:/vqtTyX6Tbgr/ylyIdjfuceCoaPQ1jp3QjBSmrXm+3NqSnHMLBpEwM1T7IzD5G62/u7xnrzA6LbFHw/sH1DvQpw0QS6NnYwE5At3gGZ9f8tY4NpQ7FErvmVyzyFqk6HLUpLFgJQC12rizsSblKUFJtqegCj9+XLoQGrWkVRboCw=,iv:RhQel3ooWSL6KsBW0XSR9u9D+q9bGqkrkX9iOukcBhE=,tag:spdCBHL4lpKfmd8806C6bg==,type:str]
  pgp:
    - created_at: "2026-05-15T15:30:17Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DA2FdwJLszpkSAQdA0Wv85xE77WqCLr27Adu+iwd/nqU79czIxHZgHy1/ggAw
        AlzbzaamFQBVfqp+Z+v38kqzgs/X5rolGXtLwxhDpF7rsMCjIEsOmxymFUzqOKy1
        0l4BlE4Gvls8oqHdda/ttPOfYfb5nJaEasBuPNxl8RtC7mAZXQuEWDABUS57hBH2
        fmI5GFhyLRMDaVvOV/zG6IYX6K8C3b/WLqYzteKbQFj+81Z0oZ0vLjVbBKduIgEm
        =z5BX
        -----END PGP MESSAGE-----
      fp: 20D22783FF50D18568CF617303615DC092ECCE99
  unencrypted_suffix: _unencrypted
  version: 3.12.2
