#!/usr/bin/env bash
set -exuo pipefail

staged_files=$(git diff --name-only --cached)

function is_shellscipt() {
	# $1: file name
	[ "${1##*.}" = "sh" ] || head -n 1 "$1" | grep -qE "^#!.*sh|^#!.*bash"
}

for file in ${staged_files}; do
	if is_shellscipt "${file}"; then
		shellcheck "${file}"
		checkbashisms "${file}"
		shfmt -w "${file}"
	fi
done

echo "${staged_files}" | xargs alejandra

echo "${staged_files}" | xargs git add
