matrix-alertmanager-token: ENC[AES256_GCM,data:eGddWCXUROSbMaXUPclK5py9JcDMdQwTDfS97DoTupY=,iv:BsquNXmhQt42S5Qm3m8utn+Lf/ZH5eg9OJs9azoTUsE=,tag:ScXtOqCZ9op0jA/YPjy8Ng==,type:str]
matrix-alertmanager-webhook-secret: ENC[AES256_GCM,data:A8gJmHn/aH0Uv8loDA/bNkjpJnb/8EY40gLkGlFBlI84UFEq+KKFTTtO,iv:RTJxUl+RGvzogeiXNNPURUqmAHjSs4hfCggnwVHgCC4=,tag:D2uZzehoqQIXAKpDW6S3ZA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aWsrcmxadGUyU3B2NzF1
        azV0b1VoTjZaUVVlOUVjNnIwSFJvMXpzWFVFCkRodGNVTlVaNEFjN1M1cXZ2TGx3
        Mzk1TFJVQktLUkNyaW9hMEk3OFJiUjgKLS0tIDNIMnF5NUZodFYxYWJQRkJoMkh4
        WmxsUkEwN09Rd1VZcnRhTER3aGZQeGMK9Zr+RElbcq6NnPStBYJPn6duzM9D27SZ
        e0vmv8e7nGqL+PEKqXTQv3UjOcOgO2KZ6mw7s8w7tciOF8o/fv3PYQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k49t7ycus0gyw37fl69y3nl3ny7vsy44p5583qs8rx6asdeeqvjqr8jlh4
  lastmodified: "2026-07-20T15:37:53Z"
  mac: ENC[AES256_GCM,data:8/iglY8Aq5EOesewvbERlFqebf38olK+tPO+3tWpg3Da22EjPtLPlNl8+6R3Avohs5AA6yr8Ab1Cep1TE0+T991DBYyJcDqzkcibO8REYtPdg4ORsoHubLMMUa9xYPnFsYrqkx+Oze/jhCc+wi7N+uaba/Ca58DPb05aCkDjLQU=,iv:wWT+f9oNmTseH/66Srq0k4fR4u6vYwpBJtI6liEiVBc=,tag:k92UwW6cfIJtz1wuf5h+YQ==,type:str]
  pgp:
    - created_at: "2026-07-17T08:47:20Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DA2FdwJLszpkSAQdA56UfoFgAnoiAvjPrQybRS9la0qd87O1I0nNOixMkQ0Uw
        LeHQVQYkG+SEIdFUJz+5dpwTeQFDfmdGUAowJH/1Kyx+Rh/UCOEXnNpxx0OdhfVO
        0lwBcEUQNS4qttUnyFwJd1orGhCUumIBlm/t0iVY0JWoPe0Lz3t41x1gN7hLuRzS
        fb3weK6ikbT8nbCHYUgQCLRX4qi2Y0MHW8TCP8PBmsZUQ1CKxZv/viDn2o3gYw==
        =oxrc
        -----END PGP MESSAGE-----
      fp: 20D22783FF50D18568CF617303615DC092ECCE99
  unencrypted_suffix: _unencrypted
  version: 3.13.1
