keys:
  - &admin age1dtl3zsquam6dy39laqk08dn9y5txrzng7zqfshvr3zjcyym58pmst8hy4r
  - &kilimanjaro age16jy52qzvaw7clfg8lvfz47xq3alg8h59xxfrm8uq9d40w8xz8arqys2fvh
  - &serengeti age16n7n3e52trwtmm6ct083ssl2ksq4undly820m888vw337fpsdypspjsw4w
  - &manyara age1k49t7ycus0gyw37fl69y3nl3ny7vsy44p5583qs8rx6asdeeqvjqr8jlh4

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin
        - *kilimanjaro
        - *serengeti
        - *manyara
