keys:
  # system
  - &admin 20D22783FF50D18568CF617303615DC092ECCE99
  - &kilimanjaro age16jy52qzvaw7clfg8lvfz47xq3alg8h59xxfrm8uq9d40w8xz8arqys2fvh
  - &serengeti age1zcwtypme4ytx3mugstqfp7d4pe00hpjxk6f40u0pq4ftnvppuyxs48cskm
  - &manyara age1k49t7ycus0gyw37fl69y3nl3ny7vsy44p5583qs8rx6asdeeqvjqr8jlh4
  - &mikumi age1de8fxy635636r8ylvj3uh8c7l4elkh4z056ekedd6tcvs0e53u4q0hzgm7
  - &tarangire age1jp2sc7nag4225nd633njwvzlp2racrst3jep2c9y84f8sw3myvasyuzz2k
  # user
  - &work-user age1742eak9s9hev9hrvkf8gk9etp8pgjgkdsc7ngelluk4se0tacdtsg4j0pd
  - &katavi-user age18y3exmqczgeq7x5ns0zgnda93et0nmmgsusgpxs4hgej8cqsyv8qclaf8m
  - &kilimanjaro-user age1d75d5z05vm9t6gen6qwrmpkzhzmt6rv4d34x0z8v7wqrf24jq92qpklrjf
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *kilimanjaro
          - *serengeti
          - *manyara
          - *mikumi
          - *tarangire
  - path_regex: infra/*
    key_groups:
      - pgp:
          - *admin
  - path_regex: systems/nixos/services/hydra/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *kilimanjaro
  - path_regex: systems/nixos/services/calibre-web/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *manyara
  - path_regex: systems/nixos/services/forgejo/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *manyara
  - path_regex: systems/nixos/services/grafana/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *manyara
  - path_regex: systems/nixos/services/gitea-actions-runner/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *kilimanjaro
          - *serengeti
  - path_regex: systems/nixos/serengeti/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *serengeti
  - path_regex: systems/nixos/services/attic/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *serengeti
  - path_regex: systems/darwin/mikumi/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *mikumi
  - path_regex: systems/shared/hercules-ci/[^/]+\.(yaml|json)$
    key_groups:
      - pgp:
          - *admin
        age:
          - *kilimanjaro
          - *mikumi
          - *serengeti
          - *tarangire
  - path_regex: homes/shared/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *katavi-user
          - *kilimanjaro-user
          - *work-user
  - path_regex: homes/darwin/work/secrets.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *work-user
