{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.my.services.kanata;

  driver = cfg.package.darwinDriver;

  # System Extensions must reside inside /Applications, not as symlinks.
  parentAppDir = "/Applications/.Nix-Karabiner";

  # macOS TCC identifies binaries by code signature. Nix store paths change on
  # every rebuild and carry only linker-signed adhoc signatures, so Input
  # Monitoring permission is lost after each rebuild. Copying to a stable path
  # and re-signing lets the TCC grant persist across rebuilds.
  kanataBinDir = "/usr/local/lib/kanata";

  upstreamDoc = "See https://github.com/jtroo/kanata/blob/main/docs/config.adoc for more information.";

  keyboard =
    { name, config, ... }:
    {
      options = {
        config = lib.mkOption {
          type = lib.types.lines;
          example = ''
            (defsrc
              caps)

            (deflayermap (default-layer)
              ;; tap caps lock as caps lock, hold caps lock as left control
              caps (tap-hold 100 100 caps lctl))
          '';
          description = ''
            Configuration other than `defcfg`.

            ${upstreamDoc}
          '';
        };
        extraDefCfg = lib.mkOption {
          type = lib.types.lines;
          default = "";
          example = "danger-enable-cmd yes";
          description = ''
            Extra configuration to include in the `defcfg` block.

            ${upstreamDoc}
          '';
        };
        configFile = lib.mkOption {
          type = lib.types.path;
          default = mkConfig name config;
          defaultText = "A config file generated by values from other kanata module options.";
          description = ''
            The config file.

            Set this to use your own full config file, which overrides
            all other kanata module options.  ${upstreamDoc}
          '';
        };
        extraArgs = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
          description = "Extra command line arguments passed to kanata.";
        };
        port = lib.mkOption {
          type = lib.types.nullOr lib.types.port;
          default = null;
          example = 6666;
          description = ''
            Port to run the TCP server on. `null` will not run the server.
          '';
        };
      };
    };

  mkName = name: "kanata-${name}";

  mkConfig =
    name: keyboard:
    pkgs.writeTextFile {
      name = "${mkName name}-config.kbd";
      text = ''
        (defcfg
          ${keyboard.extraDefCfg})

        ${keyboard.config}
      '';
      checkPhase = ''
        ${lib.getExe cfg.package} --cfg "$target" --check --debug
      '';
    };

  mkService =
    name: keyboard:
    lib.nameValuePair (mkName name) {
      # ProgramArguments calls kanata directly instead of wrapping in /bin/sh,
      # so macOS TCC checks the kanata binary itself for Input Monitoring
      # permission rather than the shell.
      serviceConfig = {
        ProgramArguments = [
          "${kanataBinDir}/kanata"
          "--cfg"
          (toString keyboard.configFile)
        ]
        ++ lib.optionals (keyboard.port != null) [
          "--port"
          (toString keyboard.port)
        ]
        ++ keyboard.extraArgs;
        RunAtLoad = true;
        KeepAlive = true;
        StandardOutPath = "/var/log/${mkName name}.log";
        StandardErrorPath = "/var/log/${mkName name}.err";
      };
    };
in
{
  options = {
    my.services.kanata = {
      enable = lib.mkEnableOption "kanata, a tool to improve keyboard comfort and usability with advanced customization";
      package = lib.mkPackageOption pkgs "kanata" {
        example = [ "kanata-with-cmd" ];
      };
      keyboards = lib.mkOption {
        type = lib.types.attrsOf (lib.types.submodule keyboard);
        default = { };
        description = "Keyboard configurations.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];

    # Copy the DriverKit app into /Applications so macOS recognizes the
    # System Extension. Symlinks from the Nix store do not work because
    # macOS requires the .app bundle to be a real directory under /Applications.
    system.activationScripts.preActivation.text = ''
      rm -rf ${parentAppDir}
      mkdir -p ${parentAppDir}
      cp -r ${driver}/Applications/.Karabiner-VirtualHIDDevice-Manager.app ${parentAppDir}

      mkdir -p ${kanataBinDir}
      cp -f ${lib.getExe cfg.package} ${kanataBinDir}/kanata
      chmod 755 ${kanataBinDir}/kanata
      /usr/bin/codesign -fs - ${kanataBinDir}/kanata
    '';

    launchd.user.agents.activate_karabiner_system_ext = {
      serviceConfig.ProgramArguments = [
        "${parentAppDir}/.Karabiner-VirtualHIDDevice-Manager.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Manager"
        "activate"
      ];
      serviceConfig.RunAtLoad = true;
    };

    # kanata must run as a system daemon (root) because the Karabiner
    # VirtualHIDDevice socket at /Library/Application Support/org.pqrs/tmp/
    # rootonly/ is only accessible by root.
    launchd.daemons = {
      Karabiner-VirtualHIDDevice-Daemon = {
        serviceConfig = {
          ProgramArguments = [
            "${driver}/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Daemon"
          ];
          KeepAlive = true;
          RunAtLoad = true;
          ProcessType = "Interactive";
        };
      };
    }
    // lib.mapAttrs' mkService cfg.keyboards;
  };
}
