{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.my.services.kanata;

  driver = cfg.package.darwinDriver;

  # System Extensions must reside inside /Applications, not as symlinks.
  parentAppDir = "/Applications/.Nix-Kanata";

  upstreamDoc = "See https://github.com/jtroo/kanata/blob/main/docs/config.adoc for more information.";

  keyboard =
    { name, config, ... }:
    {
      options = {
        config = lib.mkOption {
          type = lib.types.lines;
          example = ''
            (defsrc
              caps)

            (deflayermap (default-layer)
              ;; tap caps lock as caps lock, hold caps lock as left control
              caps (tap-hold 100 100 caps lctl))
          '';
          description = ''
            Configuration other than `defcfg`.

            ${upstreamDoc}
          '';
        };
        extraDefCfg = lib.mkOption {
          type = lib.types.lines;
          default = "";
          example = "danger-enable-cmd yes";
          description = ''
            Extra configuration to include in the `defcfg` block.

            ${upstreamDoc}
          '';
        };
        configFile = lib.mkOption {
          type = lib.types.path;
          default = mkConfig name config;
          defaultText = "A config file generated by values from other kanata module options.";
          description = ''
            The config file.

            Set this to use your own full config file, which overrides
            all other kanata module options.  ${upstreamDoc}
          '';
        };
        extraArgs = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
          description = "Extra command line arguments passed to kanata.";
        };
        port = lib.mkOption {
          type = lib.types.nullOr lib.types.port;
          default = null;
          example = 6666;
          description = ''
            Port to run the TCP server on. `null` will not run the server.
          '';
        };
      };
    };

  mkName = name: "kanata-${name}";

  mkConfig =
    name: keyboard:
    pkgs.writeTextFile {
      name = "${mkName name}-config.kbd";
      text = ''
        (defcfg
          ${keyboard.extraDefCfg})

        ${keyboard.config}
      '';
      checkPhase = ''
        ${lib.getExe cfg.package} --cfg "$target" --check --debug
      '';
    };

  mkService =
    name: keyboard:
    lib.nameValuePair (mkName name) {
      # wait4path ensures the Nix Store is mounted before attempting to
      # run kanata, which lives in the store.
      script = ''
        /bin/wait4path ${lib.getExe cfg.package} && exec ${lib.getExe cfg.package} \
          --cfg ${keyboard.configFile} \
          ${lib.optionalString (keyboard.port != null) "--port ${toString keyboard.port}"} \
          ${lib.escapeShellArgs keyboard.extraArgs}
      '';
      serviceConfig = {
        RunAtLoad = true;
        KeepAlive = true;
        StandardOutPath = "/tmp/${mkName name}.log";
        StandardErrorPath = "/tmp/${mkName name}.err.log";
      };
    };
in
{
  options = {
    my.services.kanata = {
      enable = lib.mkEnableOption "kanata, a tool to improve keyboard comfort and usability with advanced customization";
      package = lib.mkPackageOption pkgs "kanata" {
        example = [ "kanata-with-cmd" ];
      };
      keyboards = lib.mkOption {
        type = lib.types.attrsOf (lib.types.submodule keyboard);
        default = { };
        description = "Keyboard configurations.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];

    # Copy the DriverKit app into /Applications so macOS recognizes the
    # System Extension. Symlinks from the Nix store do not work because
    # macOS requires the .app bundle to be a real directory under /Applications.
    system.activationScripts.preActivation.text = ''
      rm -rf ${parentAppDir}
      mkdir -p ${parentAppDir}
      cp -r ${driver}/Applications/.Karabiner-VirtualHIDDevice-Manager.app ${parentAppDir}
    '';

    system.activationScripts.postActivation.text = ''
      echo "activating Karabiner DriverKit VirtualHIDDevice for kanata" >&2
      ${parentAppDir}/.Karabiner-VirtualHIDDevice-Manager.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Manager activate
    '';

    launchd.daemons = {
      Karabiner-VirtualHIDDevice-Daemon = {
        serviceConfig = {
          ProgramArguments = [
            "${driver}/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Daemon"
          ];
          KeepAlive = true;
          RunAtLoad = true;
          ProcessType = "Interactive";
        };
      };
    }
    // lib.mapAttrs' mkService cfg.keyboards;
  };
}
