api_token: ENC[AES256_GCM,data:Mgf0fgt6RdqoNTrWOk5NcYmvtz1mU/qNr9ev/zbVFzhTIWELENzmQQ==,iv:1ZSu9QwvgWvaiZvd0CL4TKe6D1Hz9URWegniOvAiRD8=,tag:SOlW2PsimCb4qtb6yPPGCQ==,type:str]
sops:
  age:
    - recipient: age1pk0z5nauz3extrv3kqqksl6yf433nk66jq9s3kk6xz07nnwxcddq9z7vhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZUFNQVRsMGFyT1FKU3NF
        RkVOQkNic1pYb20vTnJmcm5iLzQ3QUlPZVg0Cnc4dEc5YnlSVWt2ODkxaGpRS0VR
        MWNXNlk2blRkNHBlYWJPdTFva3kzN3cKLS0tIElVRlJoM3pQK3g5eW91dXhUeENU
        RFJITVViNFRpdU1Vb24rU21vd3NBZmcKaYCUemscCGcJK0ukAKXxLX+aucQGLf2R
        zMH3fUXY2wPF55/Yjjed8QdKPy2IIcAwrzg6EiQQiLR1SuhylP4QPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-23T09:36:50Z"
  mac: ENC[AES256_GCM,data:IWzlYKoj9afuzWXGpTpJwH2icpkeOffLbPI1iFcT6Zmn5ax5Wgtx56MRqBYyDXdGgbMn7ca6Yo4nEjlUaj3Tw2g8VD81Sk3kaMvE1dJRPUI8NoUnQhGOIgJP0KpwEEZTDcyfdjOgfoI3ZRAZum1R0R2yS0BKc3/TQFIMtmVrBfc=,iv:Xf4PQoce1CzdKMgjzwTkONL24DFE19XEqtyThBMA+R8=,tag:iBSS2NDpHkf/Oi8wCQwAzQ==,type:str]
  pgp:
    - created_at: "2026-03-08T07:32:32Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DA2FdwJLszpkSAQdAkZ3aSIyisXrwnpL/tPKn5wIIRKvVWU+hSEyZGZe0wDQw
        XHFx3NeT9CFoRbpnQgWgmLEB4myzpb6QdgIWAqeNAKtu0iz0uFL/b+J8WUf/dq4Z
        0l4BkWC1xxSVJkENwu7vd5NkDRqM7SXYPs7TxWJYT9CdHmBe9IoONYF7iAQcQ4hb
        liZ48CfHUBarZOZpE9xKJG6dNjFjbZEBsn8A8MP/jQtC2qic+sbG8OoLlNBwz3oh
        =Bofl
        -----END PGP MESSAGE-----
      fp: 20D22783FF50D18568CF617303615DC092ECCE99
  unencrypted_suffix: _unencrypted
  version: 3.9.4
