token: ENC[AES256_GCM,data:Fw4N03OZ9Ld2e1kiXdSymbgQKFKRqDQnMWR6O/Mt6NM5EA1EDBHYVyLkOdYGxgwfmZNJPCtEak0qkSIrhU2x7D+tHfWkfAz2/hHsDy/UXvvAUmrNdq/v2Ao2ObLV,iv:yuYmVrTxKhSkAnprESUqnDmCb0MM7dZF/61EKpafJ58=,tag:Q71PE/JE2v+x5nhh5GYrCA==,type:str]
sops:
  age:
    - recipient: age1pk0z5nauz3extrv3kqqksl6yf433nk66jq9s3kk6xz07nnwxcddq9z7vhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWsrZDFDT2wvak80aUNm
        WVZ6enJmNE5zOEh3V0RUNUVDNkJBTmlITzBZClBmT2s0RnRzWk5yaDBKNy9hWkxT
        OXVEbGh4cGVlZWZ6ZDY3Z1RoMThadTgKLS0tIHJ0OVNOdXRwYVRkaFpzZEhQZktG
        T2FNYXFBZjNGUkpscG5rcUlvS3Z2UU0K5L2PmIaIVeO/JeKiN/WbGcC0xgU3/4fp
        eatElHXERnNE3JbnPYLQKiJzm6FLjlVTKOEFLIyQ3CVBWNZssLHApQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T16:29:18Z"
  mac: ENC[AES256_GCM,data:sFpQCkLFzGrNqO9OaF4uBKSR+UNdLl5bsYMjeNr3mb/p6smhXKZqfJIY9Ec5N15+RhFBSRKL6ovBTF9flNHHED2rPdjZQmAhAEr7BiFNxAFdKJmRdIAngE65HXha5TWony4UxBI4TuDmV5djvh2ZONzD0HktYORv21gC/PSl4TE=,iv:D/CCTZOSu+NfkSeY2iRHjWLunMl3zCzzJAn8GeO7dlI=,tag:X9mOhWtcuWk7vb2rQSfLnQ==,type:str]
  pgp:
    - created_at: "2026-03-07T02:37:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DA2FdwJLszpkSAQdAcYlr8oXT9YLBRlvUfe0FExCCIObgFSno4Oxh6CaNaGIw
        mVt4FYXTsHmoGe6alvvk3uS0ynLLmefwKswseRfZl+uvh+qIg6PFUl343SvwiLA2
        0l4BJjTfckgwP4+2ZCHJ7xMb8aAciv7S5llFhAWbbxASFiw4Vn9A/0UHQLr48/eU
        IYQndmrzgLA60ZA6ymoTd6W0DiEjdQNwp+Q1tEHIZCFRWQ9yP1Sjq3jWd8FsgDFp
        =zIqq
        -----END PGP MESSAGE-----
      fp: 20D22783FF50D18568CF617303615DC092ECCE99
  unencrypted_suffix: _unencrypted
  version: 3.10.2
