tomoya_email: ENC[AES256_GCM,data:zreFV3aaNN7HuM4DQ3qZRPkaQT4ZGg==,iv:3/LqWvt88t8ty8s7kLQXUOoOjTu+6uHT4R5GOdlAyew=,tag:QCtXgIL7BSzNwVfsOROq3Q==,type:str]
hikari_email: ENC[AES256_GCM,data:Sy2H7k0R0I/lKHnR8nwK1ve79S1DAw==,iv:+WXURZOYvqnQ450F/7cdGzuqaUU23z9buhGp1CA98OI=,tag:g87cUDdFXtsekfsfJawosA==,type:str]
sops:
  age:
    - recipient: age1pk0z5nauz3extrv3kqqksl6yf433nk66jq9s3kk6xz07nnwxcddq9z7vhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVHZYaEZ5STdGcVBQanEz
        Q3JidTdWM2wrK1VGcnF1Qm44QU9uY0QwVWpnClRLa296S0tMNDNmTndXTU9Zb21i
        WFZScWJCaFFiOFJ1K0JOZ3ZleHJxVWsKLS0tIG1vOXJRTWVES2pZTjBNTjgxa3Vm
        N2hOYkZTV1dtN0Z4dnN3a1htWGtPRGcKvRBltax0sPUjwUFw9GcO887SZ6AB0koi
        fvIoxuGQxSo9d6p3wXLVIEZHFKBN3BQ+CZPbvzgxFOs/7zz+NFPDtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-16T06:10:17Z"
  mac: ENC[AES256_GCM,data:Ul0z2XWHdnqgrWImxieA7GC7UrwipoGsK8bGZ8UO7nvk6iVC6+Kcev6oc6UUogGY0gBBvcHDm+izPV69hgxIvrejYKNt6ZrXBT8z1gmshfy5gt5/erKsqTCdECbHsKiZXE3QFTB6jl0zRkVfsTV5mtPxR48CGsC2QwD2N6kWnX4=,iv:KoEeji91q919/ycyApahX2/mcw37QkhlEsznC7hs7PQ=,tag:N7IxUn7E8WjDCVxwMRswHw==,type:str]
  pgp:
    - created_at: "2026-05-16T06:10:17Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DA2FdwJLszpkSAQdAXZjWJ3myb6pyV7jnFZebKtVV15hQ9WS1LjN3FvfKzA8w
        p6nH9a79PPCTOWscuV3iv+3bIDUUSEDU2gwwmL8SUiKAzighTBqzDD4wAFrpmbIF
        0l4BnxET85Nkf60G2VSg40FI88r+9x02L72J2Q8xgmvPPJZggOKbMe58PjjPt2YU
        why9iPJY+XVOXBnZhdD+eBX5zyl4sNGU7zijT5Ym8T2XZeZ5AaXuSA/ufOvuYyuH
        =g93u
        -----END PGP MESSAGE-----
      fp: 20D22783FF50D18568CF617303615DC092ECCE99
  unencrypted_suffix: _unencrypted
  version: 3.12.2
