(require 'org)
(require 'ox-html)
(require 'htmlize)
(require 'nix-ts-mode)

(add-to-list 'org-src-lang-modes '("nix" . nix-ts))
(setq treesit-font-lock-level 4)

;; Emit `org-*' class names on syntax spans instead of inline color styles, so
;; assets/org-html.css owns the palette and can restyle code for dark mode.
;; Inline colors would freeze one theme into the markup.
(setq org-html-htmlize-output-type 'css)

;; Export five headline levels as real headings (default is 3). Deeper sections
;; would otherwise become plain lists with no anchor, and the sticky breadcrumb
;; only pins actual headings; five keeps every level within valid h2..h6 tags.
(setq org-export-headline-levels 5)

;; The frame styling is our own; drop Org's default <style> and scripts.
(setq org-html-head-include-default-style nil
      org-html-head-include-scripts nil)

;; Don't abort the whole documentation build over one dangling link. The
;; Japanese document is generated by po4a, so a paragraph that is still
;; untranslated falls back to English while its target heading is already
;; localized, leaving a fuzzy link with no matching anchor. Export it as plain
;; text instead of erroring so translation lag never takes the site down.
(setq org-export-with-broken-links t)

;; Inline the stylesheet and script rather than <link>/<script src>-ing them, so
;; each exported file (index.html and ja/index.html live at different depths) is
;; self-contained and needs no path juggling or extra request. The script only
;; enhances (sticky-heading compaction, a floating contents button); the page is
;; readable without it.
(defun dotfiles-slurp (path)
  (with-temp-buffer
    (insert-file-contents path)
    (buffer-string)))

(setq org-html-head
      (concat "<style>\n" (dotfiles-slurp "assets/org-html.css") "</style>\n"
              "<script>\n" (dotfiles-slurp "assets/org-html.js") "</script>"))

;; Fold the table of contents: rewrite Org's #table-of-contents <div> into a
;; native <details> so the long, deeply nested TOC does not push the body down.
;; The block contains only list markup, so the first "</div></div>" reliably
;; closes it. The title capture keeps this language-agnostic (en/ja).
(defun dotfiles-html-collapse-toc (output _backend _info)
  (replace-regexp-in-string
   (concat "<div id=\"table-of-contents\"[^>]*>\n"
           "<h2>\\([^<]*\\)</h2>\n"
           "<div id=\"text-table-of-contents\"[^>]*>\n"
           "\\(\\(?:.\\|\n\\)*?\\)\n"
           "</div>\n</div>")
   (concat "<details id=\"table-of-contents\" class=\"toc\" open>\n"
           "<summary>\\1</summary>\n"
           "<div id=\"text-table-of-contents\" role=\"doc-toc\">\n"
           "\\2\n</div>\n</details>")
   output t))

(add-to-list 'org-export-filter-final-output-functions
             #'dotfiles-html-collapse-toc)

;; Head every code block with the file it tangles to, linked to GitHub.
;;
;; The target cannot be read off the block at export time. `#+INCLUDE' splices
;; the child documents into configuration.org and leaves no trace of where each
;; block came from, while `:tangle' paths are relative to the document that
;; declares them (modules/configuration.org writes "features/nix.nix" for
;; modules/features/nix.nix). Resolving by "which candidate path exists" is
;; ambiguous: overlays/configuration.org tangles to "default.nix", and both
;; overlays/default.nix and modules/default.nix are real files. So read each
;; document separately, while its directory is still known, and key on the block
;; body, which #+INCLUDE copies verbatim.
(defconst dotfiles-source-url "https://github.com/natsukium/dotfiles/blob/main/")

;; Documents that declare `:tangle' targets, and the prefix their paths are
;; relative to; mirrors the addprefix calls in the Makefile's tangle rules.
;; modules/features/emacs/{early-init,init}.org are left out on purpose: their
;; blocks carry no `:tangle' header, and Nix assembles them into init.el at
;; build time, so no file in the repository corresponds to them.
(defconst dotfiles-tangle-sources
  '(("configuration" . "")
    ("modules/configuration" . "modules/")
    ("overlays/configuration" . "overlays/")))

(defvar dotfiles-tangle-map nil)

(defun dotfiles-src-block-target (src-block prefix)
  "Repo-relative file SRC-BLOCK tangles to, or nil when it tangles nowhere."
  (let ((params (or (org-element-property :parameters src-block) "")))
    ;; `\s-' rather than a literal space on purpose: the Makefile finds what to
    ;; tangle by grepping this document for a `:tangle' header followed by a
    ;; space, so a space here would offer it this regexp as a file to build.
    (when (string-match ":tangle\\s-+\\([^ ]+\\)" params)
      ;; Capture before the next `string-match' overwrites the match data.
      (let ((target (match-string 1 params)))
        (unless (or (equal target "no")
                    ;; Never exported, so never rendered. Skipping these also
                    ;; keeps the boilerplate stubs, which repeat verbatim across
                    ;; documents, from colliding in the map.
                    (string-match ":exports\\s-+none" params))
          (concat prefix target))))))

(defun dotfiles-build-tangle-map (suffix)
  "Map each exported block body to the file it tangles to.
SUFFIX is \"\" for the English document and \".ja\" for the translated one. The
map is rebuilt per language because po4a translates comments inside code, which
changes the body it is keyed on."
  (let ((map (make-hash-table :test 'equal)))
    (dolist (source dotfiles-tangle-sources map)
      (with-current-buffer (find-file-noselect (concat (car source) suffix ".org"))
        (org-element-map (org-element-parse-buffer) 'src-block
          (lambda (src-block)
            (let ((target (dotfiles-src-block-target src-block (cdr source))))
              (when target
                (let* ((body (org-element-property :value src-block))
                       (previous (gethash body map)))
                  ;; Keying on the body is only sound while no two exported
                  ;; blocks share one. Fail loudly rather than link to the wrong
                  ;; file if that ever stops holding.
                  (when (and previous (not (equal previous target)))
                    (error "Blocks tangling to %s and %s have identical bodies"
                           previous target))
                  (puthash body target map))))))))))

;; Turn noweb references into links to the block that defines them, so the
;; expansions a tangled file is assembled from can be followed by reading.
(defvar dotfiles-noweb-names nil
  "Block names that unambiguously identify one block in the current export.")

(defun dotfiles-collect-noweb-names (tree _backend _info)
  "Record every block name defined exactly once in TREE.
A name used twice cannot be anchored: names are scoped to the document that
declares them, but #+INCLUDE merges every document into one page, where an id
has to be unique. nix-config, defined by both configuration.org and
modules/configuration.org, is the only one here, and stays unlinked."
  (let ((counts (make-hash-table :test 'equal)))
    (org-element-map tree 'src-block
      (lambda (src-block)
        (let ((name (org-element-property :name src-block)))
          (when name (puthash name (1+ (gethash name counts 0)) counts)))))
    (setq dotfiles-noweb-names (make-hash-table :test 'equal))
    (maphash (lambda (name count)
               (when (= count 1) (puthash name t dotfiles-noweb-names)))
             counts))
  tree)

(add-to-list 'org-export-filter-parse-tree-functions
             #'dotfiles-collect-noweb-names)

(defconst dotfiles-noweb-token "nowebref0%s0"
  "Stand-in for a noweb reference while its block is fontified.")

(defun dotfiles-noweb-html (name)
  "Rendered reference to NAME, linked when NAME is anchored."
  (if (gethash name dotfiles-noweb-names)
      (format "<a class=\"noweb-ref\" href=\"#%s\">&lt;&lt;%s&gt;&gt;</a>" name name)
    (format "&lt;&lt;%s&gt;&gt;" name)))

(defun dotfiles-fontify-noweb (original code lang &rest args)
  "Swap noweb references out of CODE, fontify, then restore them as links.
Rewriting the fontified markup instead is not viable: nix-ts-mode reads a
reference as a search path and splits it across spans seven different ways
depending on the surrounding syntax, and three of those straddle span
boundaries, so replacing them would unbalance the markup. A bare identifier is
a single token in any grammar, so it survives fontification in one piece and
can be swapped back without touching a tag."
  (let (names)
    (setq code
          (replace-regexp-in-string
           "<<\\([a-zA-Z0-9_-]+\\)>>"
           (lambda (match)
             (let ((name (match-string 1 match)))
               (push name names)
               (format dotfiles-noweb-token name)))
           code t t))
    (let ((html (apply original code lang args)))
      (dolist (name (delete-dups names) html)
        (setq html (replace-regexp-in-string
                    (regexp-quote (format dotfiles-noweb-token name))
                    (dotfiles-noweb-html name)
                    html t t))))))

(advice-add 'org-html-fontify-code :around #'dotfiles-fontify-noweb)

(defconst dotfiles-src-lang-names '(("emacs-lisp" . "elisp"))
  "Header text for languages whose Org name reads poorly.")

(defconst dotfiles-src-container "<div class=\"org-src-container\">\n")

(defun dotfiles-html-src-block-head (original src-block contents info)
  "Prepend a header naming what SRC-BLOCK produces.
A block that tangles links to its file, a block that noweb references point at
shows and anchors that name, and the rest name their language."
  (let ((html (funcall original src-block contents info)))
    (if (not (string-prefix-p dotfiles-src-container html))
        html
      (let* ((target (gethash (org-element-property :value src-block)
                              dotfiles-tangle-map))
             (name (org-element-property :name src-block))
             (anchor (and name (gethash name dotfiles-noweb-names) name))
             (language (org-element-property :language src-block))
             (label
              (cond
               (target (format "<a class=\"src-path\" href=\"%s%s\">%s</a>"
                               dotfiles-source-url target
                               (org-html-encode-plain-text target)))
               (anchor (format "<span class=\"src-noweb\">&lt;&lt;%s&gt;&gt;</span>"
                               (org-html-encode-plain-text anchor)))
               (t (format "<span class=\"src-lang\">%s</span>"
                          (org-html-encode-plain-text
                           (or (cdr (assoc language dotfiles-src-lang-names))
                               language "")))))))
        (concat dotfiles-src-container
                (if anchor
                    (format "<div class=\"src-head\" id=\"%s\">" anchor)
                  "<div class=\"src-head\">")
                label "</div>\n"
                (substring html (length dotfiles-src-container)))))))

(advice-add 'org-html-src-block :around #'dotfiles-html-src-block-head)

(setq dotfiles-tangle-map (dotfiles-build-tangle-map ""))
(find-file "configuration.org")
(org-html-export-to-html)

(setq dotfiles-tangle-map (dotfiles-build-tangle-map ".ja"))
(find-file "configuration.ja.org")
(org-html-export-to-html)
