name: Setup Nix with Cachix
description: Setup Nix environment with Cachix configuration
inputs:
  signingKey:
    description: Cachix signing key
    required: true
  authToken:
    description: Cachix auth token
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix
      # Installing Nix in single user mode causes `man-cache` build to fail on Linux,
      # so nixbuild/nix-quick-install-action cannot be used
      # https://github.com/nix-community/cache-nix-action/issues/60#issuecomment-3561402982
      uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
    - name: Setup cachix
      uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
      with:
        name: natsukium
        signingKey: ${{ inputs.signingKey }}
        authToken: ${{ inputs.authToken }}
        extraPullNames: nix-community
