name: Setup Nix with Cachix
description: Setup Nix environment with Cachix configuration
inputs:
  signingKey:
    description: Cachix signing key
    required: false
  authToken:
    description: Cachix auth token
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix
      # Installing Nix in single user mode causes `man-cache` build to fail on Linux,
      # so nixbuild/nix-quick-install-action cannot be used
      # https://github.com/nix-community/cache-nix-action/issues/60#issuecomment-3561402982
      uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
    - name: Setup cachix
      uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
      with:
        name: natsukium
        signingKey: ${{ inputs.signingKey }}
        authToken: ${{ inputs.authToken }}
        extraPullNames: nix-community
