name: Setup Nix with Cachix
description: Setup Nix environment with Cachix configuration
inputs:
  signingKey:
    description: Cachix signing key
    required: false
  authToken:
    description: Cachix auth token
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix
      # Installing Nix in single user mode causes `man-cache` build to fail on Linux,
      # so nixbuild/nix-quick-install-action cannot be used
      # https://github.com/nix-community/cache-nix-action/issues/60#issuecomment-3561402982
      uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
    - name: Setup cachix
      uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
      with:
        name: natsukium
        signingKey: ${{ inputs.signingKey }}
        authToken: ${{ inputs.authToken }}
        extraPullNames: nix-community
