"$schema" = "https://starship.rs/config-schema.json"

format = "$shell$all$line_break$character"

[shell]
fish_indicator = "󰈺"
powershell_indicator = "󰨊"
disabled = false

[custom.remote-container]
when = """ test "$REMOTE_CONTAINERS" """
symbol = "🐋"
format = " in $symbol "

[gcloud]
disabled = true
