tailscale-authkey: ENC[AES256_GCM,data:seylIxJ9YJs0LlZY0eKjillp1IK0WzAyeROMgH6mcd63C5anG7QQ2yFKGNJDt7NnA72Z2C/qh7cUE1q+SJw=,iv:cwxjQzoHwmuwGA9slTJ7GtUBWqp/iLV1Z9rUHiJAe7o=,tag:REpoJPvHye1cjEHOZWZ8HA==,type:str]
wifi: ENC[AES256_GCM,data:j4kX1jPPD9XWS18PdQRgDRPA7TTJBDR3iIKHRV90ALqjEda1Mg6mYzOhUWrgnnRwzVGt1nYijYpp+26k3r1485OIi6Lz,iv:ak4oP557CTv4ASKUka2xCVi1sQ6ee6VIhrltchxHIt8=,tag:llHn7Qb+zFHBL4lkD3fdvg==,type:str]
miniflux: ENC[AES256_GCM,data:t1TSSESaimECBnh667Qtn6glnZMHkIRtcLO3qZnnUkhvj1WaZ4ejkk7arZaYmKsWTQLbvsDmUSbq,iv:OXvOQhQHfEWvXLH4Vk3hUBv8Gdvr1KelJD99+yZBaSY=,tag:K0MZTaZEH2ss1iKPiS+cSA==,type:str]
login-password: ENC[AES256_GCM,data:u7WkSIkb3drjNLIVmnagN5hSYgOJX4F4ZltAcV+Yp7+pt4n0mzFt8QELWtVq8XrvSne908mmqCUpApnle0PMd7WlFCXZdcFUpw==,iv:enZECR3pgcLB30fGyNPDJYeLwtRjeBrsdSFT/URXooE=,tag:pnUiCMgnxehSeDnbzPVjMA==,type:str]
gh-token: ENC[AES256_GCM,data:gWo1CnfAsUy3u1CbzGkEwZaNV+ouGd0gHq/FS2vtJVmU7FqU0Djbuh/i+fyTGEu8jTs5xqT64iEGuEODggHi5E9gKiEUCOAPs4Sr2LhZZ0hvnIv9D+gcOO9cHRKhTA20HIza8PXR,iv:V6HopN3Md07B12RiKehEU7EVvPboFVyy5gpOwdLFP3Y=,tag:IfhNUVre2ya5TlR516XV4Q==,type:str]
cloudflared-tunnel-cert: ENC[AES256_GCM,data:XczBWkstP8JCjlwls9nWCVmAHg0ieJQjvQWOdj5zFJMJ6cMRXLgQGYFZrkBstOzpCqc2FX89YDbrIPLXxOpEMSMa2K2yfo6h3/faPE1F1SGxdv/W6fP9UoN/GJxhFWK5TtEm3QUC7N/TPhg2iA1H6sSESFomSG7ZnsGgnOaWzyg14J2TZoBOKkJHEJRHdQF+B9q+Ts5YzMyS1It700h4QQ3vfF00e/QcQ+kzVoaLt5szXrJ8cMRjKPVGZtZlblfmowc4eV0uXfigGzvMJNoMh/UzJnHllNEgJyXFioIiwlaJbP1InIbeAGWWXIspOBUH0Wx5Re+pv+3KGOULXoyZo0d2g73aj28D/RGqS//uTcQPcFhl4qbZ+f+qAxPz5q1GI2In8zj3TbJLZY1n7m0Y3PpCZLNzU3XwVz3PEKGmF7GtNHmfJLlYBJvHVDZ8NA7IyceV0ursVQveGCwcUbHIK79y/UOQ4Jm4EJhlSjF57vtBOxZ/LItH6vaXNqL+qEnLR2ZhDIz67ETo5odTSwW2VWcJwXhOlUarz2LRLRW91vKz1hcrQ4kw37v0osVbPrdW2Iz8xeCjVGddAaT2NcwF2Q6xVsokAetOJmeghAzP5nX/HxOlQVFmuceTZqGr14lml5s1uC2GtbwY9XLGC4wJHssbowdaHZAObIaolb6fE44KoGuY+aqhM+1Q0jACnNjGXSxTbN0BtocDJJC5Pt71og7NqobYIp9fbHWLz0ywIuwx5ap1HGIojsLq4yZTbthZTAYhlbZoL+f4NOp7UaQk9iMFj1++IwhxYapQxFAEkaQZYhm/DM5x7FpK3uPFPBSxxibXU2+h4ducj0lGK8Fk6i76F8cIA/UZTVHVGCKROgBluc/bGHOcSzgcAi6vg/rsP6GSvmtdFu7gLDSDt9OzLtS7Xw8tEWmChu+N1msSdzSlgOSvbmpcL/967bqOc/sJ5GH0/S/k0dkWv6dj9rbjNFwnIg219hgLTH8Or5NXaQqY+0L0qE3w/GuAS4ZAZJ8umRFqDgERll5tr9qLC/N+xESkuBSyrOjp8cIGJd6ocAPsUaYfQZxTbeYRU2cZ/YBnuxOFPMI0xRpyXMl+jinVUIwsh9HpfnOZYpzfnUD7PYopXR8yr9iICNBsAjOsQmjBkNu76r/XHgWpIe4W9YK6b6zu0xMQd/FpT4ajbtms9FybUQ2P2OouFR+zUzA7r8DN9MJTjfdTMuS2/xyj0Df15gX6UDXPQHWCInr2QN9PuYtleNAkcw4kvBceT6OXQUYvhrrX33aARTOg8GjXcwAliF7AmNoRDBGvPU4bUgoXe09A8VW32DyMw0fyYQNur9DVY+x4t8yirboKlnuDO8jN6XRYYFwIbBOKWTylFpWw4QfQR2rKsydjZ2ZbHd0sljQJBPu1cFyH0v8QWGxgaOqdnCV6l8Q6OpTV5SAWiMS9XUDP5koisW+VtfCiJBL3vdXJkYnm3VMlI4j72XAysS7cbKs9xkec9nH/pBExslvqhtLXhfdMfsG2r2dgSZrGzFnDn5AhZM8F31WkJ+khyhBWJIvlkoIyRrBI95TeVTV8hkk9gDBH9mccikYyZQ9SfMz3N9JlQPE9bXpQKWL1yzYTifO0u+ZTLj971e/ckV9SMviLF7DdC/w8KC4Gpc8S2qLoH4gpkx86AsFk+7BRRs3kts1M8sFkn8JDqnsAWRbpKruPwTNpGVO/DljZctNU7MwHy65kKct4dyoldEGFv/FyqJIS741eXv2C0T/dYtErESw4YOSGlwZJWYAz+ufGX5GSeRWIqGwsDeq7sluFt68DqyZzgfbs4TIfeAB2c5TO4xJT7RetagRs1MZ54KZcZpnU4RPwDfYzRvuWpOhlUJS41c+ELNXywarG08CbNYV3RSy+pStN5VdjlswxAZQ3nA5nGwUqpv+0z46RFyPJhhBtjRipsUZ2X7tv7meS8UWHLYvQEwIAWnCMvGnrpxbjNiTR8Iovf4/Dz86G8eIC6Xiy7bW8ab4kW/NA2scGptoXqlbdMA+9gs8SV0dCXkNZx5zV7DuZN4hN1cTpe1k7Jk7e3pH/IWczyj9/0eeIzIE9ix2VUNqhnBC8S0B3rF5vkqJO6GO47Qd/0/1x3T6FbjTXHfw5gmLBFei0md5I5sLN67BQVAxksEFUMPcf1dAecf85gODpCJrmbKaBkJjH05/tvVnUTxsAYPTqXL2NbIWlkXztubgDHBpGEdLNm5Tp3AjP59ssef3nAHOzR8dwNRRGYbvJe1uqOrYVolC/zlEPBQExDzD669TvhNwbqHPZRVtFbZ6tGgVQ5sZyFbE3HcstNgwLdPrChUp4QEU4X60EZOwYXokoVoJji3PEX1ApmrjvX9VjQb2wqsKz0apbk16vaYWG9jcW/UUW4ivzDEfwcc5b9JRnR7BHk10gj1WFb76VfK/UaAlmcHMEPMCxGDx7RzfsAPAAOjNyZU6bSqpo/2N7BK4aQdK5yfbtdJSZ4kPi7AFTcTBGAcLG0fSkTQEP2ykwe1OWdsXH4Hagbkf+loPOo7lShQq3EE2tYo8jv84colcl+mscQypGL4nt53/9ty8C,iv:je5MkcYOEFKhB8ErH3USDWgltSSiAJoc1BU1X7bIPzI=,tag:y8UjF/DakoxKsgBybjRc7Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16jy52qzvaw7clfg8lvfz47xq3alg8h59xxfrm8uq9d40w8xz8arqys2fvh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRTB1d0srWm1VUFlzaUtu
        WWtPVTdEOURjc1pYUHplcTFWT01jcWVVM0E0CkxWeGNzcXJOenNiM0tSS3NvcjNw
        dllKcTNkWGNjSEUxZnhqSW56SXM0dTgKLS0tIEwyYlpRdHozbHlsdE5qN2FOOGJC
        Sk1pNklBaiszTEdGNXhESE5vcVZRN1EKXD9lXBtWy9o7kY3wrbXjQUDhd57bvq7G
        Ey9/bFCiH0gpKQe0zyAQ/unOvHAFw7vCuG40p77DyVenZDkxHVe0qg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1zcwtypme4ytx3mugstqfp7d4pe00hpjxk6f40u0pq4ftnvppuyxs48cskm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZi9sYjlaOGtSS3BXZjJV
        QTlSVjREbEE1QzNTRlJwcVBTTWpVQWE3dVc4Ck1mUjQ4ZlhsNmZveVRyWHEvYlFo
        anYyazlRbGJsV3RTb0Z1ZzdJbk5NRHcKLS0tIE9sR1Fmb3dsNHFxOGR0emtGV0tT
        QWo2TkhLclpnRUhBWkNmbEFQTXZEUFUKBa1duHhs2x4/XXRezpgumRuuC1dR8Vew
        uZ4cyk9RVYHdSm5NYSYkQB5xzung0raaBrYOxQZlKSc8UyRXeX7Ppw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k49t7ycus0gyw37fl69y3nl3ny7vsy44p5583qs8rx6asdeeqvjqr8jlh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTjE4NVA1dk96U1BpWndv
        amVJci9QNXFUZ1RQTGVXdm9rMEwvb3FzSm1zCitlYnhzMldBZkJYdSsxRldGaTB1
        bit6TjBWcFBFV1AzYjJERkx5UmhHbkkKLS0tIFlOaUpJS052ellhM1I0NTJDUGpJ
        L3hGLzI2SFg2eTRNUCtRcXAwUjNtU1UK/sCFAd7JBQWN6woeHvLyHJjX99RfpNM2
        YUiSZKCaRwqkG1AFy6N1tQ3ixqXXRj1MN/03jE7ocTwkQL5TKgFUPg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1de8fxy635636r8ylvj3uh8c7l4elkh4z056ekedd6tcvs0e53u4q0hzgm7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWEZSOEdzTUlodHdJUlgy
        YXlBbTZaK09HMnhIQlIxLzJTa05lckNvSG5VClI3ZkNBMUVlc3BJb0t6S0thMHIv
        S256QnNPREpZc0J4S2JOUTFNWVJkb28KLS0tIFFSU2ZYYzhic0J4YnJPamVrMFVi
        cFZsdGhzSmkwS1I5TGxrYkovMzdrekEKUiTDESNGXV+kEHz2EDxoHMQ8/57YsPP5
        sqVO6xf/cwuT2NRxMrzn8FDMhzzxJ1Eb+Bs3NTUGBaw4pLW0+D7Fhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-14T00:50:42Z"
  mac: ENC[AES256_GCM,data:ox1fFrtxNzrk5tJbXKOBLVuALLryAuXuhTnTxF8LMam0i4sb2deRHUGljWtR93Utbl4Miw0biWdce4poSK03P+8q1Umm5E86pT6ENVYAfrw4/G74DFIPBFnEGLaVfYRaZr5YemjAiXOxZ3GscB3rITOFtUWIcFJLxjbL2C2eAPc=,iv:+T8aDgyqJAUyt2GXDqmr/aNGQOVSKSMsWt90Gz4Fd/s=,tag:Ku61s3YOuJZ2XdwEzyx4RQ==,type:str]
  pgp:
    - created_at: "2024-11-26T13:23:48Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DA2FdwJLszpkSAQdAGHoOvUoM5RH8o9YHxcaLs6UaA7qU6ky81Xp2oMMWuAQw
        cCB+4MDlSe0iI3b0Mf7ectsrwkuR1PwqrnldO7QfGZygUj8YxIVHgVRW2+e0I42q
        0l4BaWY1JFrv5gsk2B52IY/nC/SYfGuClKDQlnC4g2La93S2rD5aWBKEfyhxbtYg
        d8Km1NX1NByCOZhjIcBdSPrD6bh793Yeg6Zcdul5YEYCmpk1ugKRhmHkVzK6MQi7
        =Tp1U
        -----END PGP MESSAGE-----
      fp: 20D22783FF50D18568CF617303615DC092ECCE99
  unencrypted_suffix: _unencrypted
  version: 3.9.4
