tailscale-authkey: ENC[AES256_GCM,data:31Js1btciXkfGyqJsNENdihypZRsMFuIdnJ4OtS8Es+z/fBt/Hg1qb1FRMohK8vnpnNG5IevigmZl7sZZg==,iv:ljpyP8WDDsHjOe27h6D/YzTaRLiVa64HN7TP+RPqMcg=,tag:fgIhh+VwNAB4D54VPeXyiA==,type:str]
wifi: ENC[AES256_GCM,data:j4kX1jPPD9XWS18PdQRgDRPA7TTJBDR3iIKHRV90ALqjEda1Mg6mYzOhUWrgnnRwzVGt1nYijYpp+26k3r1485OIi6Lz,iv:ak4oP557CTv4ASKUka2xCVi1sQ6ee6VIhrltchxHIt8=,tag:llHn7Qb+zFHBL4lkD3fdvg==,type:str]
miniflux: ENC[AES256_GCM,data:t1TSSESaimECBnh667Qtn6glnZMHkIRtcLO3qZnnUkhvj1WaZ4ejkk7arZaYmKsWTQLbvsDmUSbq,iv:OXvOQhQHfEWvXLH4Vk3hUBv8Gdvr1KelJD99+yZBaSY=,tag:K0MZTaZEH2ss1iKPiS+cSA==,type:str]
login-password: ENC[AES256_GCM,data:u7WkSIkb3drjNLIVmnagN5hSYgOJX4F4ZltAcV+Yp7+pt4n0mzFt8QELWtVq8XrvSne908mmqCUpApnle0PMd7WlFCXZdcFUpw==,iv:enZECR3pgcLB30fGyNPDJYeLwtRjeBrsdSFT/URXooE=,tag:pnUiCMgnxehSeDnbzPVjMA==,type:str]
gh-token: ENC[AES256_GCM,data:gWo1CnfAsUy3u1CbzGkEwZaNV+ouGd0gHq/FS2vtJVmU7FqU0Djbuh/i+fyTGEu8jTs5xqT64iEGuEODggHi5E9gKiEUCOAPs4Sr2LhZZ0hvnIv9D+gcOO9cHRKhTA20HIza8PXR,iv:V6HopN3Md07B12RiKehEU7EVvPboFVyy5gpOwdLFP3Y=,tag:IfhNUVre2ya5TlR516XV4Q==,type:str]
cloudflared-tunnel-cert: ENC[AES256_GCM,data:XczBWkstP8JCjlwls9nWCVmAHg0ieJQjvQWOdj5zFJMJ6cMRXLgQGYFZrkBstOzpCqc2FX89YDbrIPLXxOpEMSMa2K2yfo6h3/faPE1F1SGxdv/W6fP9UoN/GJxhFWK5TtEm3QUC7N/TPhg2iA1H6sSESFomSG7ZnsGgnOaWzyg14J2TZoBOKkJHEJRHdQF+B9q+Ts5YzMyS1It700h4QQ3vfF00e/QcQ+kzVoaLt5szXrJ8cMRjKPVGZtZlblfmowc4eV0uXfigGzvMJNoMh/UzJnHllNEgJyXFioIiwlaJbP1InIbeAGWWXIspOBUH0Wx5Re+pv+3KGOULXoyZo0d2g73aj28D/RGqS//uTcQPcFhl4qbZ+f+qAxPz5q1GI2In8zj3TbJLZY1n7m0Y3PpCZLNzU3XwVz3PEKGmF7GtNHmfJLlYBJvHVDZ8NA7IyceV0ursVQveGCwcUbHIK79y/UOQ4Jm4EJhlSjF57vtBOxZ/LItH6vaXNqL+qEnLR2ZhDIz67ETo5odTSwW2VWcJwXhOlUarz2LRLRW91vKz1hcrQ4kw37v0osVbPrdW2Iz8xeCjVGddAaT2NcwF2Q6xVsokAetOJmeghAzP5nX/HxOlQVFmuceTZqGr14lml5s1uC2GtbwY9XLGC4wJHssbowdaHZAObIaolb6fE44KoGuY+aqhM+1Q0jACnNjGXSxTbN0BtocDJJC5Pt71og7NqobYIp9fbHWLz0ywIuwx5ap1HGIojsLq4yZTbthZTAYhlbZoL+f4NOp7UaQk9iMFj1++IwhxYapQxFAEkaQZYhm/DM5x7FpK3uPFPBSxxibXU2+h4ducj0lGK8Fk6i76F8cIA/UZTVHVGCKROgBluc/bGHOcSzgcAi6vg/rsP6GSvmtdFu7gLDSDt9OzLtS7Xw8tEWmChu+N1msSdzSlgOSvbmpcL/967bqOc/sJ5GH0/S/k0dkWv6dj9rbjNFwnIg219hgLTH8Or5NXaQqY+0L0qE3w/GuAS4ZAZJ8umRFqDgERll5tr9qLC/N+xESkuBSyrOjp8cIGJd6ocAPsUaYfQZxTbeYRU2cZ/YBnuxOFPMI0xRpyXMl+jinVUIwsh9HpfnOZYpzfnUD7PYopXR8yr9iICNBsAjOsQmjBkNu76r/XHgWpIe4W9YK6b6zu0xMQd/FpT4ajbtms9FybUQ2P2OouFR+zUzA7r8DN9MJTjfdTMuS2/xyj0Df15gX6UDXPQHWCInr2QN9PuYtleNAkcw4kvBceT6OXQUYvhrrX33aARTOg8GjXcwAliF7AmNoRDBGvPU4bUgoXe09A8VW32DyMw0fyYQNur9DVY+x4t8yirboKlnuDO8jN6XRYYFwIbBOKWTylFpWw4QfQR2rKsydjZ2ZbHd0sljQJBPu1cFyH0v8QWGxgaOqdnCV6l8Q6OpTV5SAWiMS9XUDP5koisW+VtfCiJBL3vdXJkYnm3VMlI4j72XAysS7cbKs9xkec9nH/pBExslvqhtLXhfdMfsG2r2dgSZrGzFnDn5AhZM8F31WkJ+khyhBWJIvlkoIyRrBI95TeVTV8hkk9gDBH9mccikYyZQ9SfMz3N9JlQPE9bXpQKWL1yzYTifO0u+ZTLj971e/ckV9SMviLF7DdC/w8KC4Gpc8S2qLoH4gpkx86AsFk+7BRRs3kts1M8sFkn8JDqnsAWRbpKruPwTNpGVO/DljZctNU7MwHy65kKct4dyoldEGFv/FyqJIS741eXv2C0T/dYtErESw4YOSGlwZJWYAz+ufGX5GSeRWIqGwsDeq7sluFt68DqyZzgfbs4TIfeAB2c5TO4xJT7RetagRs1MZ54KZcZpnU4RPwDfYzRvuWpOhlUJS41c+ELNXywarG08CbNYV3RSy+pStN5VdjlswxAZQ3nA5nGwUqpv+0z46RFyPJhhBtjRipsUZ2X7tv7meS8UWHLYvQEwIAWnCMvGnrpxbjNiTR8Iovf4/Dz86G8eIC6Xiy7bW8ab4kW/NA2scGptoXqlbdMA+9gs8SV0dCXkNZx5zV7DuZN4hN1cTpe1k7Jk7e3pH/IWczyj9/0eeIzIE9ix2VUNqhnBC8S0B3rF5vkqJO6GO47Qd/0/1x3T6FbjTXHfw5gmLBFei0md5I5sLN67BQVAxksEFUMPcf1dAecf85gODpCJrmbKaBkJjH05/tvVnUTxsAYPTqXL2NbIWlkXztubgDHBpGEdLNm5Tp3AjP59ssef3nAHOzR8dwNRRGYbvJe1uqOrYVolC/zlEPBQExDzD669TvhNwbqHPZRVtFbZ6tGgVQ5sZyFbE3HcstNgwLdPrChUp4QEU4X60EZOwYXokoVoJji3PEX1ApmrjvX9VjQb2wqsKz0apbk16vaYWG9jcW/UUW4ivzDEfwcc5b9JRnR7BHk10gj1WFb76VfK/UaAlmcHMEPMCxGDx7RzfsAPAAOjNyZU6bSqpo/2N7BK4aQdK5yfbtdJSZ4kPi7AFTcTBGAcLG0fSkTQEP2ykwe1OWdsXH4Hagbkf+loPOo7lShQq3EE2tYo8jv84colcl+mscQypGL4nt53/9ty8C,iv:je5MkcYOEFKhB8ErH3USDWgltSSiAJoc1BU1X7bIPzI=,tag:y8UjF/DakoxKsgBybjRc7Q==,type:str]
sops:
  age:
    - recipient: age16jy52qzvaw7clfg8lvfz47xq3alg8h59xxfrm8uq9d40w8xz8arqys2fvh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSHhONDVDT1JCRG9HN2Fa
        V2RDOEh0elpramVpVVR5UlkwMi9OdlRHUmlJClJiK2laYmIraFlKdWFsUnFxckFZ
        MFlWRE0yRWZFUGIyT01UbU0wWWtNeWcKLS0tIC9GK0lmM3ZiT3V0MTBWbVRuWkVp
        OFhVWTE5cHFxbjN4U0JMM0pBeU9oSU0KID4hS/s67o48ocUiF40hNXcrEp5xeOsm
        a/lnkW/hvMjB8ewwgKDjuzKNgL6kbd+Lg/NY8dXG4k0Wthc0UyxIXw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1zcwtypme4ytx3mugstqfp7d4pe00hpjxk6f40u0pq4ftnvppuyxs48cskm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTmI5V1JuWHFnQ1ZHanQy
        ZCtVRDBWQ3BoUmk2bXVSLzVUbGlJajJibFRvCmdRa2U2Z3QzdnJpTlExMUliYjVn
        SmZ6TlAwNnhIazUzeW1QMEk5a1VJdWcKLS0tIG15akxSajZzSEZXRkkyT1MwOG1P
        NzNWM2pIYS9TYXdsQXFFRGN1NnZyZkUKR3pUWRxMfD9laJHCMJsNz2geJFEYOLuG
        OarX870Jzwcx+BKDogsOfsN2oKwEgJFsYGcutWC5uODZdjcbDGJ3nQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k49t7ycus0gyw37fl69y3nl3ny7vsy44p5583qs8rx6asdeeqvjqr8jlh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMGhzK1RlRnN6ZGduL2NB
        aUZ6Y3pLZ0hKblAzVTJ1QVNSb1EyUEV4VGlBCjZXOWd2aEcwL2hKWVpYNGtyeUZO
        YlVuZ3lvanpPamRCTDArQ0M5elEzRlEKLS0tIHBXV2ZTbWlhZlpmaGtyRDVUdlZM
        eGs4eDRtT2FaV0tsWUNsRllKc0xUYkEK/ggHdSJmkiKUjRCH4avLu0REWXgcRMMn
        p9UbpuUJZRsLBohSVaFY9iYfFMLcgwZGcMX/0hh7XSb/GeU057hX9A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1de8fxy635636r8ylvj3uh8c7l4elkh4z056ekedd6tcvs0e53u4q0hzgm7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dkZ1YlZTR0E1N2l2QVlM
        M2tWRHZqdHBuck9aSTJXSjZ2UkZGdCtTMEZjCjRYZzZ3QmZhSHM4NXNQT0FVVkkz
        U21kdTNZWVpzb0VOWEJ3aE5FVXl2cjgKLS0tIHVCWCtkN1VFMHd1RVU1OGo4Yi9r
        dFJ4NFJjbVIzSUZ5Yk5tSHdGcmdEMk0KqijlydOT1lWcGeOg26iHOtaLmD4SCs/B
        a8qWklnVeMqYKA4DiU8Wq4TX5mudXtnKLNr0EGaAu6FLpUb+blmjQQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jp2sc7nag4225nd633njwvzlp2racrst3jep2c9y84f8sw3myvasyuzz2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUDY1ZjRJVkR2dlU1aHFF
        bURDQnNxd3BuV3dDWlRTSjBmWExVTW9GcVgwCk44Qk95OUVZcHFleStRb01LYUhT
        dTFDTW1SbUdWNEJJWW11TGFyWjgrSUUKLS0tIFBuQUVzNGJmUjRzWkYzc0lBS3Z4
        ZFVIRHMvYUo1WVBySkpZSTBRMWNwU3MKp76P9pL3qmxNvhe6xa7gp56umbpbWr7X
        LX97xDSFYZ2sFDAFEQ5gjdJf18TGr2TqvgrWZ1eLAnrBx/aMLQfxdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-23T03:55:47Z"
  mac: ENC[AES256_GCM,data:8ln5uPD6J4i1FGBenQh7XuTFp17B/rFoEV/LInBSOHQK4iaERBDwbHW78jnLQGvc2jMPPFicB0fbcQxrNHG1o1V7e8FOrwnslD2UEQEaKxWKmcNadxpSt4609mWZhpbW773sExrLJ+HWMAtQRb4Jy21TGsZgzV5j/8o6pUdJhMs=,iv:MOtJaNNOnZ8/5CYvQDZOCAYUVmR72UoiPt4Et+kcslA=,tag:huxC6lTTKcRJClc/B9n9NQ==,type:str]
  pgp:
    - created_at: "2025-06-01T06:42:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DA2FdwJLszpkSAQdABa3QMmYRQ3BJZBx1DZ9cGI+9TRnFGw+zEK4MN96dJFsw
        mN2lHp95rpGCAcjx+Cz/5AHMp6y0EUKt1Ail9VOnd3xJCXflJpWYDQ53opmWohde
        0l4BcH9gYSDs6xI1fgOXDoq4gN6TSnNfF/SbNM+4cyDMwLl7HT9pWvkm2pfrn6VW
        yKnBr1wCj9R34xL2d0Sfbe5EkY1sOUKI77hTKF89rwK/CNNno6ZArvq/mGOk//RA
        =ET4v
        -----END PGP MESSAGE-----
      fp: 20D22783FF50D18568CF617303615DC092ECCE99
  unencrypted_suffix: _unencrypted
  version: 3.11.0
