tailscale-authkey: ENC[AES256_GCM,data:9l+XTgEFojIh7z6uY3ZxuUfSxyKBQUkqSaLBA8L/GqilOcLHdTCo3gziXceiJDh9znJxWeHsm1ML,iv:gxKUFwVGhVKvHJx/+BCfihrNfYrYFE0g4bwXEVKdwvM=,tag:xW04qzPuCHoTk5SQFdMoOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dtl3zsquam6dy39laqk08dn9y5txrzng7zqfshvr3zjcyym58pmst8hy4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRzFUSHdwN2JyWHFWREVM
            T3QzRXJ6eDNRRVZ0Y2ZKZVk4L29kbjE4RDJzCjdGdnJ2cXEweEtsS2p2cjVCOTEz
            MUpzQmZRcnI2OUlBb3VqSkpNNlNHTHcKLS0tIHdRUDdHaDlWYm9YaS9kNWU5SFI3
            bWpCVis1eFpIWmN1QlkyVGRvNHRwSmMKd3osUT6SUAEddnShZAnShqKVvSlTkRUs
            Spj37NELrQtpumMwufaqry4FZ6jrnz8CbXpSRHMp3sWSvQo+vLyfuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16jy52qzvaw7clfg8lvfz47xq3alg8h59xxfrm8uq9d40w8xz8arqys2fvh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbWorQjRGVXVrUzFwM1VF
            R1ZIL2t0Y25nei9mYzBQM3Rua0craDZFWmhBCnhWblVKZXpaREhYUW1ZbXk4MlI2
            cHRSbk1iSEp0Ylc0RDFGTEtmdWRwd2cKLS0tIFMwNHVOanZockkyYWZUR2ppMGNZ
            akl5NGJWMWNmSUFmVjFBVHpTT0MzOXcKfy1a2hCaaw0HDUfKVP3CXu9SH73ruIJY
            Jux+8ld3OutTDOR4QhpdG5y4RKNGsmXkz8MRrXbrHC//fIOj7SG4Yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16n7n3e52trwtmm6ct083ssl2ksq4undly820m888vw337fpsdypspjsw4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSFpEbWQ4ZWVqYWRqZEhl
            QXRteUYwTVFNcnVIclI1TDlhOTZlb1ZqUEc0CjlqbGhNSldmUnJic3ZiaXV2M1pY
            aEVvdDNWTFlVWlQyd1BxZ2preTJJWmMKLS0tIHA2c1gvM1JoQUZBaTVUVHlSTFhJ
            YStkcVZPYjJJUTdVaWJFclo0dEg0NE0KtZz3TpugPI8zhnvqtDEKe9zUgHqjbzrg
            QZHv2eOgZ3kfo+54AHUmki4A3NzGfFq/x3+vhcdBzxA27dC+NYj4fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k49t7ycus0gyw37fl69y3nl3ny7vsy44p5583qs8rx6asdeeqvjqr8jlh4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid29xZnNBNHNPMmpDbUtO
            dHJFYnVYbGtCbDZ3V2VrLzVmNGppSFZZYkE0CmNOd0YrcVNZSHNZRk0rcnhvWFlR
            QXFBZ1gyVGtCbHcvRzdnREtuRTh4dWcKLS0tIFpOWVdjdUlrMGI4RThkNnpONjEv
            MUV3NnRoMDRoZjRYR1h1SU1zMEdxaDgKnMnd7S3d8XlWtHLgUplGR2fjOTe6NhfX
            LEcne90dhx9n//69exEPNiRRhrw+UxmHHUPCN8Snk6lKjXelD1Hu+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-01T03:04:34Z"
    mac: ENC[AES256_GCM,data:X6i86z4hfvGchYCBC3c9rW1/f6gEuncDUANtphACM2YsENktTfrpHgOPfHaCg7opLM7obHAARL3pZIb96BlF41TTKCK7DdrZCMNLsOv6N2tgDZNS7BktOrfoyPKnadq5pz1gwfcK/lr92WtDnVbX64SOBxJ4a5RY/1ZJ0LBkRD8=,iv:z5LdsXcJgqEYFBmb9mPVYexTfMYj1J74gK1xLGyUOoA=,tag:uCQpyjkINayrc0pWuNVnlA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
