tailscale-authkey: ENC[AES256_GCM,data:NilC3Cq0RkbYY3hVHowXE6QJPs4R85yU6u60A4s/f5gzxXRsnADhCm1pVm5TKCw/R8pXqiWUfAHQudJhDiQ=,iv:wnb1O3ASJ13DEEqEowUyWJjC9ujH/R3Gqvh8uD4SiMc=,tag:cxAFbrFZ9iV7gwN+t5Gvag==,type:str]
wifi: ENC[AES256_GCM,data:j4kX1jPPD9XWS18PdQRgDRPA7TTJBDR3iIKHRV90ALqjEda1Mg6mYzOhUWrgnnRwzVGt1nYijYpp+26k3r1485OIi6Lz,iv:ak4oP557CTv4ASKUka2xCVi1sQ6ee6VIhrltchxHIt8=,tag:llHn7Qb+zFHBL4lkD3fdvg==,type:str]
miniflux: ENC[AES256_GCM,data:t1TSSESaimECBnh667Qtn6glnZMHkIRtcLO3qZnnUkhvj1WaZ4ejkk7arZaYmKsWTQLbvsDmUSbq,iv:OXvOQhQHfEWvXLH4Vk3hUBv8Gdvr1KelJD99+yZBaSY=,tag:K0MZTaZEH2ss1iKPiS+cSA==,type:str]
login-password: ENC[AES256_GCM,data:u7WkSIkb3drjNLIVmnagN5hSYgOJX4F4ZltAcV+Yp7+pt4n0mzFt8QELWtVq8XrvSne908mmqCUpApnle0PMd7WlFCXZdcFUpw==,iv:enZECR3pgcLB30fGyNPDJYeLwtRjeBrsdSFT/URXooE=,tag:pnUiCMgnxehSeDnbzPVjMA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16jy52qzvaw7clfg8lvfz47xq3alg8h59xxfrm8uq9d40w8xz8arqys2fvh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWnh2d0lrUmZ5Y05FTjEv
        b0F1YmQ2ZDdlQXJuTFZteXNvMW5pWmZmS2tvCm8xMmRIWER5aXVDVTR2aWl6QVhm
        WkVWVWVxajc2cTJEVzRVRjUxWWYvR0EKLS0tIEdsOW16c3dDSTJDbkdKdHpjYkg1
        cC9tMm5iMXlENUVCaHg0OHJWdlVhWGcKySFKOzQXRlka/JvSPWR+P3EX8DLl6vnw
        JMQgvhVEt6nT/oKXFI8eHwvlSoi7M4L7gFi1srzGAFR1k7mepl9oXg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1zcwtypme4ytx3mugstqfp7d4pe00hpjxk6f40u0pq4ftnvppuyxs48cskm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WTJDRXlDY05oTzdpVldC
        UTZZTTYwZEZ2NGpwUXJIblUwZGNUajQ3MnlJCjhXVDlubWpiYWFuUUJ5MlV4aFVi
        UjJVRjkvOGFuQ1lTN0hsaTdOZkMwOVkKLS0tIHJWZ0VYYVVIR2hwVlJHOTdZWk9E
        OENXNndwVTVzc1BuQ1o0VUNpTGIyM1EK1pP6T44atucXO1mev44bGXqh0JSvxAv3
        344B1ex77fOHhopjQ5flq3cYdYf/94jDyF745PlcbhFz0GvXGENqmg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k49t7ycus0gyw37fl69y3nl3ny7vsy44p5583qs8rx6asdeeqvjqr8jlh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTDdML2pXQlFLTU9LNFJV
        cDBkNmJMVkk2aXlWMlhLa2NZQldoeDhMUFRzCnVINEVQUTJ0M0xzdVhmWWduVVky
        aktyWUV4OTFjUzhWQjBoRm1uTGxLYVEKLS0tIElib2ZZaCtGOThNTXBsNzZ3eGxC
        Y1dSTTRoWmlqZkpQaUNYdjdtTk5UYkkKqmPiBcap7E4fGL688JXPY6LqaivQ1DaH
        KBIMaqsui8n2g/8MN/HTQK5+P9Ek2pNySHcWS+46tRaVxQSK/E7B4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-21T08:07:24Z"
  mac: ENC[AES256_GCM,data:15g+y7m5C9dr/mu988oVjZa30ncJXQInJ+0bem1xE5sJLsT63uH+wGZMIxIygLqSnOmYoZLGj+uKkO+gtOvUHHMtEvYHPzSwoqmEHuEOudJTv/MwqsevRif8B6S5tmQy+moMG+Zoy7MtGN5H+giqzBqAM3Q86ebEyMBW+tPiDmg=,iv:j3p3lq0pwZzHhZcOJu65pxJRmPOGdJ1o13+/04b5fF0=,tag:qpz3+8gS8m3JxFpHpqKIAg==,type:str]
  pgp:
    - created_at: "2024-09-21T08:05:01Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DA2FdwJLszpkSAQdAL0IsWs+xoyELqCyFotrjWmO1T4yrJiDYhFnsw5w2jAsw
        w2TtxpJqbcr5p1t9AP2wgL34jEjPIzd/v8vA1zlNWPRb9ACxSw9qVf89rLciapYq
        0l4BvxKKlLnl1K2znvw6R9X0fCicjIIvPm5JTFm/tr6QyjA6A0DSvVBopi+zFvsw
        Bgi4Gg4OakFg6nMFF2bVMnTZbrMRnFyl9b3DNxPdZC9Ja1AlBzRZYO15P8GjBzuS
        =TKsM
        -----END PGP MESSAGE-----
      fp: 20D22783FF50D18568CF617303615DC092ECCE99
  unencrypted_suffix: _unencrypted
  version: 3.9.0
