tailscale-authkey: ENC[AES256_GCM,data:bqGadQBd3JSTGFxIzXp18h/GgEFmo/mFJp77QMqCgoXoks4fik7LsxVAeevKOEfeXCKCVSUZ/GByEk6Tdo4=,iv:HUsoE1z6nmCxTd+FcjENUwI//5ZBKypSRHwVrA24x9Y=,tag:Evn4/jf/nTnpnnVY0BE4ag==,type:str]
wifi: ENC[AES256_GCM,data:qgO1et/iX1UFf58EcsCGyyzLkDhUTYf4Pwl9Gwe7i9a9dpkAEJVEiwjulb8sdL9T5fFxwrfeOCOU4a1Txv4KAVHtSGZd,iv:RkeHvn9l8QUKjmGnTQmQe2V8boiDEzEpoh6V8MI1XRY=,tag:XARcUSU3HwhKYz0xjzW73A==,type:str]
miniflux: ENC[AES256_GCM,data:oUAdIRYg6rWXUBH3mfhy24UgBq0kzfgpooSp6YnqSYUvsejesnDBvNwGs9N5kvYCR5B4TAS5xhT1,iv:OK3NcLiY0Zm2W1PrF82bvdsUnb4jp+GFj7RiRqjhQ0Y=,tag:JhKN0andnswbnFFIdtnRdg==,type:str]
login-password: ENC[AES256_GCM,data:6l08S8bf1uIgbLKhyvWbsYyRc3j+3OjNM8aEiXZawoYaqpZm5X+7+ewpgqp9kJsHvxCQzqSnl2E8v+OkyDwYSQPvT0OQEorPoQ==,iv:4BqW9/clsR7M5tNZP5W+2/oluCMG1V7FeJALK8x3nMA=,tag:wrJM/9OphA7+7oc1U6HdQg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dtl3zsquam6dy39laqk08dn9y5txrzng7zqfshvr3zjcyym58pmst8hy4r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Vit6K0JVb2JoeTBUdmtl
        SFQrUEUyYVhSVFQzZFFPdDRYdXZKYUVQTENBCjBhTnlWR1liOUxKbDR3YzFEM1dS
        T0pqZ0plRW53bnMyc1dNcEhxMzRkVDAKLS0tIFAvRWxPTC9uZHpaMU9KVUlqWHNF
        RDBvSnVCbElJTEY0SWIrcERsekVqLzQKX8XVG6YfLsY6jDwzs0YmmwBJuKGUAfLm
        uvlyY38MM2oUnvKOSNTNirvTN53J32iPosYPlTMUHMrrgJj+L+Rypw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age16jy52qzvaw7clfg8lvfz47xq3alg8h59xxfrm8uq9d40w8xz8arqys2fvh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOHRPaDB6UjFXZ0d1c1Nl
        ZENFc2RtNjNVRmlVSHpZMnlReWNZRDRDeWx3Ci9FT1FHY0hYR0dldHVsbVZPYVJQ
        SC9qOElxTXlneTQrVnpOOS94bkdKZUkKLS0tIHFkWnB0WUcrVm01S3FhcHgydFVi
        SXc5elNsSjBqSUhjdW5XdTRLMUhPdG8K5Id7nrwHFYtdY++gUDDXuQW5KIi1brOZ
        7ol/u1FgUDiuBtjQDCsNLs3sb3D9EpsH0fMqOXiu6G/TPXeEyzNETA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1zcwtypme4ytx3mugstqfp7d4pe00hpjxk6f40u0pq4ftnvppuyxs48cskm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTlFoeTVsQUNCWjNVZ1h0
        MzdLMytIRktJSDBGb0hsVHBTNTFsRmNmRkR3Ckd5SnQ3Y2x2aFg1amhZSnJFbEZL
        d0hxZ1hsZFlzVEN6b29VZHZxeXV1aEkKLS0tIGZCYStLQjVuclpSUEROYnllNE4y
        L0VxeU81amZxQmQwY2pKZjU5SjkyNFkKoDodGf9tDRSZmo9DzYsHBcryyyW+r3nC
        OrB/jiHEciahR9dY7kH+73io9TqATwNKEH64LT6TBClDeHZS3xlEsg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k49t7ycus0gyw37fl69y3nl3ny7vsy44p5583qs8rx6asdeeqvjqr8jlh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOENBV3ZWWkxRc2Y0SzQz
        WXJQT0VxeWZ2RmM0VGg5ajlYdEpidXBkTURrCnlZU0RCcXdwYThoUy8wWUh5MFB2
        ZWhISEVuVWo4Q1paSkFmd0FzQ2RIUU0KLS0tIDhwTEhZQUszWTVvRXlmc1JtK1F4
        c0JLZlRIOWNXSUROc3YrMmgydjRQRUkKfX4JROEwjCdGeDTQw5eWs14QiphKHzYQ
        wrkjRFWFGGDaqYc9jEyPzbPFL6ft5vnz0coHOsreL0HYuLe5MMzfUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-04-04T23:12:46Z"
  mac: ENC[AES256_GCM,data:knx2nQQ+lshhQcz4Wc1ou357FML1TYf2bw+MzXtNR15r3GKErJ7kx0tSC5wMO/j0RCvrq9jM86sGwwJEV/vg2xlynDhx4i2aBk50w71abwD7DOqCPpVWVRRL3x/p2xeP4PjyIdkh5hzow/ZBI4sKbe2Eny8TF+pXh6zn/CE4+LQ=,iv:3890sGSsDtwJWYor6FV1Wxh1ETyOdKmHyximn15TafY=,tag:CM+tDWeYgDWWsas6McT5ug==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
